# -*- coding: utf-8 -*-
"""reduce_cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPF05pIlTUJPLgmGl4-o0z72ZIf8w4ko
"""

#!/usr/bin/env python3
import sys

for line in sys.stdin:
    line = line.strip()
    if line:
        # Output each cleaned row
        print(line)